sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sagnik-roy7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sagnik-roy7/docker-react npm run test
